export { HealthScreen, type HealthScreenProps } from "./app.tsx"
export {
  createBoardClient,
  createAuthClient,
  createHealthClient,
  createBoundedReconnectPolicy,
  ServiceRequestError,
  type AuthClient,
  type BoardClient,
  type BoardClientOptions,
  type BoardConnection,
  type BoardConnectionHandlers,
  type BoardConnectionScheduler,
  type BoardConnectionState,
  type BoardReconnectPolicy,
  type BoardSocket,
  type BoardWebSocketFactory,
  type HealthClient,
} from "./client.ts"
export {
  createCredentialStore,
  CredentialStoreError,
  getTerminalSessionCredentialPath,
  type CredentialFileSystem,
  type CredentialPathOptions,
  type CredentialStore,
  type CredentialStoreErrorCode,
  type CredentialStoreOptions,
} from "./credentials.ts"
export {
  MIN_TERMINAL_HEIGHT,
  MIN_TERMINAL_WIDTH,
  TerminalShell,
  type ShellMode,
  type TerminalShellProps,
} from "./shell.tsx"
export {
  STICKY_NOTE_TEXT_DEBOUNCE_MS,
  createStickyNoteDebouncer,
  validateStickyNoteEditorText,
  type StickyNoteEditorTextValidation,
  type StickyNoteDebouncer,
  type StickyNoteDebouncerOptions,
  type StickyNoteTimer,
} from "./sticky-note-editor.ts"
export {
  applyCanvasNavigation,
  canvasCoordinateToScreen,
  canvasRectIntersectsViewport,
  createCanvasNavigationState,
  getCanvasPanelWidth,
  getCanvasStickyNoteCardHeight,
  getCanvasViewportSize,
  CANVAS_MAX_COORDINATE,
  CANVAS_MIN_COORDINATE,
  CANVAS_PANEL_WIDTH,
  CANVAS_STICKY_NOTE_CARD_WIDTH,
  CANVAS_STICKY_NOTE_CARD_VERTICAL_OVERHEAD,
  type CanvasCoordinate,
  type CanvasDirection,
  type CanvasNavigationState,
  type CanvasRect,
  type CanvasViewportSize,
} from "./canvas-navigation.ts"
export { STICKY_NOTE_WIDTH, wrapStickyNoteText } from "./sticky-notes.ts"
